# ============================================================
# 捨て写 - Codemagic iOS ビルド設定
# ============================================================
# リポジトリに codemagic.yaml を置き、Codemagic でアプリを追加すると
# このワークフローでビルド・TestFlight 配信ができます。
# https://codemagic.io でアプリを追加 → リポジトリ接続 → ビルド実行
#
# 事前に Codemagic の Code signing identities で以下を設定すること:
# - App Store Connect API キー（.p8）
# - iOS 証明書（Distribution）
# - プロビジョニングプロファイル（App Store）

workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Akifumi.H.trashsnap
      vars:
        XCODE_WORKSPACE: "sutesho.xcworkspace"
        XCODE_SCHEME: "sutesho"
        BUNDLE_ID: "com.Akifumi.H.trashsnap"

    integrations:
      # ↓ Codemagic「Teams」→「Integrations」→「Manage keys」で表示される API キー名と完全一致させる
      app_store_connect: Codemagic_App

    scripts:
      - name: Install npm dependencies
        script: npm ci

      # リポジトリに ios/ がない場合（別ブランチなど）は prebuild で生成
      - name: Prebuild iOS if needed
        script: |
          if [ ! -d ios ] || [ ! -d "ios/$XCODE_WORKSPACE" ]; then
            echo "ios/ or workspace not found, running expo prebuild..."
            npx expo prebuild --platform ios --no-install
          else
            echo "ios/ already present, skipping prebuild"
          fi

      - name: Install CocoaPods
        script: cd ios && pod install

      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # 初回は submit_to_testflight: false で IPA だけビルドし、手動アップロードしても可
